#spring에서 application.properties 또는 application.yml은 환경설정파일
#yml형식은 계층구조를 가진 가독성 좋은 형식
server:
  port: 8081

# 아래는 jdbc의 기본 db 연결 설정. jdbc 뿐만 아니라 mybatis. jpa 등 spring의 대부분의 db 관리기술에서 사용
# 스키마는 사전생성필요, 테이블의 경우 jdbc/mybatis는 사전생성필요
spring:
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/board  # board 는 스키마명
      username: root
      password: test1234
# jpa를 사용하기 위한 환경설정  // mariaDB : mysql라고 씀
  jpa:
    database: mysql
#     innoDB 를 쓰겠다는 설정 (innoDB : DB엔진 종류로 대부분 이렇게 쓰임)
    database-platform: org.hibernate.dialect.MariaDBDialect
#     ddl : create alter drop => 테이블(&컬럼)의 구조를 자동생성 여부 : true
    generate-ddl: true
#     jpa(인터페이스 명세)의 실질적인 구현체는 hibernate패키지 내에 있음
    hibernate:
#    ddl문 자동생성에 대한 모드(create, update, validate) 설정
#    create: 매번(서버재시작마다) table을 전체 drop후 재생성 - 프로젝트최초구성시
#    update: 엔티티의 변경사항만 alter 를 적용, 기존데이터 유지 (추가만 해주고, 삭제는 안됨/ 컬럼길이도 변경안됨(varchar255->varchar50)등 ) - 개발서버목적
#    validate: 실제DB와의 차이점을 check만 하고 ddl문 실행X(콘솔에 변경사항만 출력) - 운영서버목적
      ddl-auto: create
#    콘솔창에 ddl, dml 등의 쿼리를 출력하여 보여주는 옵션
    show_sql: true

# Mapper파일(mybatis의 실질쿼리파일)의 위치를 명시
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  # ** : mapper하위 폴더 전부 포함,  *.xml : xml형식파일 전부

jwt:
  #  인코딩된 문자 32자 이상 필요.(특수문자) : base64 encoder 웹사이트 활용
  #  beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5