#spring에서 application.properties 또는 application.yml은 환경설정파일
#yml형식은 계층구조를 가진 가독성 좋은 형식
server:
  port: 8081

# 아래는 jdbc의 기본 db 연결 설정. jdbc 뿐만 아니라 mybatis. jpa 등 spring의 대부분의 db 관리기술에서 사용
# 스키마는 사전생성필요, 테이블의 경우 jdbc/mybatis는 사전생성필요
spring:
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/board  # board 는 스키마명
      username: root
      password: test1234
# Mapper파일(mybatis의 실질쿼리파일)의 위치를 명시
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml  # ** : mapper하위 폴더 전부 포함,  *.xml : xml형식파일 전부
